### PR TITLE
Also apply indentation rule to scenario's below rules

### PR DESCRIPTION
**Pull request by RomkeVdMeulen**

### CODE REVIEW

**Comment by RomkeVdMeulen** [comment]
@avysotskaya Build seems to be broken because of a misconfiguration.

**Comment by avysotskaya** [comment]
@RomkeVdMeulen thank you for PR!
Could you fill in the description and provide some details on this change please (what is the issue, what's expected, and what has changed)? 🙇‍♀️

**Comment by RomkeVdMeulen** [comment]
Expected: the indentation rule is applied to all examples under a Rule

Actual: the indentation of the Rule itself is checked, but anything underneath it is not

**Comment by avysotskaya** [comment]
Replaced with https://github.com/avysotskaya/gherkin-lint-ts/pull/7 (fixed issues and added tests)

**Pull request closed without merging**
